### ISSUE TITLE
Broken returned  class from arrow function.

### ISSUE THREAD

**Issue by snuggs** [bublejs/buble#122]
First of all ZOMG when I saw this project moved to Github @Rich-Harris. As you know i've been following (AND USING) bublé on all my projects for a couple years now. Gets the job done except in two cases.

```javascript
const Foo = bar =>
(/* This code breaks compiler without parens */
class Baz {}
/* le sigh */ )

Foo ('bat') // class Baz {} 
```

I did notice a slew of Arrow function messing up transpilation issues but haven't gone through all the issues yet.

Lastly...and not relative to this Issue but I need to know for the past 6 months. How do I enable string template literals? 😂 

Thanks for the awesome tool! Keep it rocking. Some of us lo-key 🔑  depend on it. Hi-key even.

**Comment by adrianheine** [comment]
`const Foo = bar => class Baz {}` compiles for me fine with current master. What output do you get?

**Comment by snuggs** [comment]
@adrianheine not certain as i've just been wrapping in `(` `)` I should check. Appreciate looking out for this.
Can finally [update this line of code](https://github.com/devpunks/snuggsi/blob/master/component/index.es#L1) if what you say is correct. Thanks homie! <3

**Comment by mourner** [comment]
This works: https://buble.surge.sh/#const%20Foo%20%3D%20bar%20%3D%3E%0Aclass%20Baz%20%7B%7D%0A%0AFoo%20('bat')%20%2F%2F%20class%20Baz%20%7B%7D%20
