### ISSUE TITLE
Non string keys are not excluded from rest object

### ISSUE THREAD

**Issue by exe-dealer** [bublejs/buble#149]
```
const source = { 1: 'one', 2: 'two' };
const { 1: _, ...rest } = source;
console.assert(!(1 in rest));
```

this test is failed when compiled with buble

```
function objectWithoutProperties (obj, exclude) { var target = {}; for (var k in obj) if (Object.prototype.hasOwnProperty.call(obj, k) && exclude.indexOf(k) === -1) target[k] = obj[k]; return target; }
var source = { 1: 'one', 2: 'two' };
var _ = source[1];
var rest$1 = objectWithoutProperties( source, [1] );
var rest = rest$1;
console.assert(!(1 in rest));
```

it uses indexOf which does strict equality so non-string keys are not ommited

**Comment by adrianheine** [comment]
Thanks for the report! This could be fixed during compile-time by writing strings into the `exclude` array, right?
```js
function objectWithoutProperties (obj, exclude) { var target = {}; for (var k in obj) if (Object.prototype.hasOwnProperty.call(obj, k) && exclude.indexOf(k) === -1) target[k] = obj[k]; return target; }
var source = { 1: 'one', 2: 'two' };
var _ = source[1];
var rest$1 = objectWithoutProperties( source, ['1'] );
var rest = rest$1;
console.assert(!(1 in rest));
```

**Comment by exe-dealer** [comment]
> Thanks for the report! This could be fixed during compile-time by writing strings into the `exclude` array, right?
> 
> ```js
> function objectWithoutProperties (obj, exclude) { var target = {}; for (var k in obj) if (Object.prototype.hasOwnProperty.call(obj, k) && exclude.indexOf(k) === -1) target[k] = obj[k]; return target; }
> var source = { 1: 'one', 2: 'two' };
> var _ = source[1];
> var rest$1 = objectWithoutProperties( source, ['1'] );
> var rest = rest$1;
> console.assert(!(1 in rest));
> ```

if you are asking me I think yes, 'writing strings' solution will cover all cases

**Comment by adrianheine** [comment]
Cool! So, currently, the code looks like this:

https://github.com/Rich-Harris/buble/blob/29eb1271e84a62a5b754a32252d3298759198893/src/utils/destructure.js#L141-L147

That basically means that all `key`s that are `Identifier`s and not computed will be quoted. This just has to be extended to cover `key`s that are `Literal`s with a numeric `value`. Do you want to try that?

**Comment by exe-dealer** [comment]
its not enough just to wrap numeric literal in quotes because of following cases 
```js
const obj = { '0.1': 'foo', '100': 'bar' };
const { .1: a, 1e2: b, ...rest  } = obj;
```
This conversion can be at compile time but this requires much more code and time, so i'm suggesting pr with runtime fix. Also my pr fixes non-string computed keys like

```js
const { [1+1]: foo, ...rest } = obj;
```

**Comment by exe-dealer** [comment]
hmm.. I forgot about case that user can redeclare String identifier

**Comment by adrianheine** [comment]
No, actually, if you use the `value` field of a numeric `Literal` `key`, you get a number, not the raw string. So with `const { .1: a, 1e2: b, ...rest  } = obj;`, the `value` properties should be the numbers `0.1` and `100`.

**Comment by adrianheine** [comment]
But you're right about non-string computed keys!

**Comment by adrianheine** [comment]
I don't think I want to consider the case that people redeclare `String` (or `Object`). That's going to break a lot of things anyway.

**Comment by adrianheine** [comment]
btw, I opened tc39/test262#2089.

**Comment by exe-dealer** [comment]
> No, actually, if you use the `value` field of a numeric `Literal` `key`, you get a number, not the raw string. So with `const { .1: a, 1e2: b, ...rest } = obj;`, the `value` properties should be the numbers `0.1` and `100`.

I updated pr
