### ISSUE TITLE
Removes comma in first object literal of a function with line comment in arguments

### ISSUE THREAD

**Issue by AngusFu** [bublejs/buble#175]
Weird bug. The following screenshot describes better than words.

![image](https://user-images.githubusercontent.com/8180186/49722524-f37f3580-fc9f-11e8-9559-d88268c9fd2b.png)

BTW, I got the function from Vue dist file [vue.esm.js](http://unpkg.com/vue@2.5.19/dist/vue.esm.js) at line 4384.

```js
function createComponentInstanceForVnode (
  vnode, // we know it's MountedComponentVNode but flow doesn't
  parent // activeInstance in lifecycle state
) {
  var options = {
    _isComponent: true,
    _parentVnode: vnode,
    parent: parent
  };
  // check inline-template render functions
  var inlineTemplate = vnode.data.inlineTemplate;
  if (isDef(inlineTemplate)) {
    options.render = inlineTemplate.render;
    options.staticRenderFns = inlineTemplate.staticRenderFns;
  }
  return new vnode.componentOptions.Ctor(options)
}
```

**Comment by iamareebjamal** [comment]
This prevents me from using buble in a vue project

**Comment by AngusFu** [comment]
@iamareebjamal As a solution for now, just exclude vue in buble plugin/loader options, since all files in `vue/dist` are pre-transpiled.

**Comment by chris-morgan** [comment]
Two minimised test cases:
```js
function x(a//
){return{b:1,c:2}}
```
```js
(a//
)=>({b:1,c:2})
```
In each case it improperly strips the comma after `b:1`, leaving `b:1c:2`. Looks to affect the first object literal with more than one element in the function, if the function has at least one argument and a line comment immediately before its arguments’ closing paren.

**Comment by anttikissa** [comment]
Bumped into a similar (same?) bug in https://github.com/rollup/rollup-plugin-buble/issues/13, from where I condensed another test case:

```
['x'].forEach(function () { } // this comment causes the bug
);

['x', 'y', 'z'].forEach(console.log)
```

If the comment "this comment causes the bug" is present, the result is `['x' 'y', 'z'].forEach(console.log)`. If the comment of stripped, it works. Bublé version 0.19.6.

It looks like this bug breaks not only Vue, but also the latest version of ReactDOM (https://unpkg.com/react-dom@16/umd/react-dom.development.js).

**Comment by anttikissa** [comment]
And like I mentioned in the other issue, my workaround for this for now: strip comments before running code through buble (in my case, using the rollup plugin rollup-plugin-cleanup).

**Comment by adrianheine** [comment]
Thanks for the report! I'm pretty sure this is an issue in my [src/utils/removeTrailingComma.js](https://github.com/Rich-Harris/buble/blob/master/src/utils/removeTrailingComma.js).
