### ISSUE TITLE
Tagged template literal breaks arrow function

### ISSUE THREAD

**Issue by lettertwo** [bublejs/buble#190]
…or maybe arrow function transform breaks tagged template literal?

Example:
```js
const src = "() => tagged`template literal`";

const { code } = transform(src, {
  transforms: { dangerousTaggedTemplateString: true }
});

eval(code);
```

Expected:
`code` is valid javascript and can `eval` without error.

Actual:
`code` errors on `eval`: 'Unexpected identifier`.

See repro on [code sandbox](https://codesandbox.io/s/210vmqrjwy?fontsize=14&module=%2Fsrc%2Findex.js)

**Comment by adrianheine** [comment]
Nice catch! Apparently this issue is specific to having an input start with an arrow function expression (or some other syntax element whose start is modified) and include a tagged template expression.
