### ISSUE TITLE
trailingFunctionCommas causes an infinite loop on calls with commented arguments

### ISSUE THREAD

**Issue by mourner** [bublejs/buble#192]
The following code (a pretty common pattern) causes Buble v0.19.7 to freeze, getting stuck in an infinite `for` loop (try pasting it in the [REPL](https://buble.surge.sh)):

```js
foo(
  1 // bar
);
```

This doesn't happen with `trailingFunctionCommas: false`. cc @adrianheine

**Comment by adrianheine** [comment]
Related to #175.
