### ISSUE TITLE
Custom `React.Fragment` pragma for JSX

### ISSUE THREAD

**Issue by ClassicOldSong** [bublejs/buble#198]
Now we can customize JSX pragma for `React.createElement`. But [here](https://github.com/bublejs/buble/blob/ecc42f5685810a966bd53b77866028f5322ac7ac/src/program/types/JSXOpeningFragment.js#L5) shows that buble now hardcodes fragment expression as `React.Fragment` which is not really a good idea. Can we make fragment pragma customizable? Such as adding an option `jsxFrag` to the option list?

Here we can see [babel has already supported customizing fragment pragma](https://babeljs.io/docs/en/babel-preset-react). Hope buble can add this soon.

**Comment by ClassicOldSong** [comment]
I'll see if I can submit a pull request on this

**Comment by mourner** [comment]
Fixed in #199
