### ISSUE TITLE
Parsing code with carelessly crafted comments hangs node at 100% CPU

### ISSUE THREAD

**Issue by strongholdmedia** [bublejs/buble#202]
I have this test case. 
_(It was part of a way bigger block, I just managed to narrow it down to this)._

As it is, _it removes the comma at the end of line 15_. It also removes it if it is in the middle of the line, I tested it. _(And as such, derails buble-loader when used with webpack, as this is surely a syntax error.)_

If I remove the line comments at the bottom - _it always works_.
If I swap the two imports at top - _it works_. Strange.

If I remove the block level comment COMPLETELY (with the code inside), it _hangs with node using 100% CPU and not doing anything in 8 hours_.

**This seems to me an optimistic regular expression greediness issue.**
But I am unsure due to the hang (that was the original issue I've found).
_That's why I am less eager to offer a more specific title for this issue._

Test case:
```javascript
const JSShim = require("./lib/helper/js-shim");
const elm = require("preact-compat").createElement;

function Test(props) { }
Test.prototype.render = function render()
{
    return elm("div", { className: "col02" },
        this.state.enabled && !this.state.readOnly
            ? elm(
                "a",
                {
                    className: "vs button",
                    title: this.props.application.labels.controller.buttonCaptionWhatever /*,
                    onClick: JSShim.bind(function(event) { return this.props.removeClick(this.props.index, event); }, this) */
                },
                elm("span", { className: "fas fa-2x fa-times text-danger" })
            )
            : null
// elm(
// )

    );
};

module.exports = Test;
```

**Comment by strongholdmedia** [comment]
I am fairly sure this is related to #175, but it is not a duplicate, as it is said to be resolved and fixed.

**Comment by mourner** [comment]
@strongholdmedia can you try this out with the master version? #175 has been fixed but we didn't have a new release on NPM yet.

**Comment by strongholdmedia** [comment]
Thanks for the heads up.

**I can indeed confirm that in the master version, all issues seem rectified.**

In fact I was dumb, since I thought that the "3 months ago" NPM publish date meant _after_ this version.

_So please make a release, if possible, as I am absolutely not keen on having github and its apparently stochastic rate limits in our deployment pipeline._

**Comment by strongholdmedia** [comment]
Duplicate of #175
