### ISSUE TITLE
Object.assign extra empty object when using spread operator

### ISSUE THREAD

**Issue by manferlo81** [bublejs/buble#203]
I believe this is not the intended behavior, if it is, please just close this issue.

I setup this example to show my point, this is not a real life example.

```javascript
const obj0 = { key: "value" };
const obj1 = { name: "john", age: 30, ...obj0 }
const obj2 = { ...obj1 }
```

I am getting...

```javascript
var obj0 = { key: "value" };
var obj1 = Object.assign({}, {name: "name"}, obj0)
var obj2 = Object.assign({}, obj1)
```

I believe `obj1` should be...

```javascript
var obj1 = Object.assign({name: "name"}, obj0)
```

[see here...](https://buble.surge.sh/#const%20obj0%20%3D%20%7B%20key%3A%20%22value%22%20%7D%3B%0Aconst%20obj1%20%3D%20%7B%20name%3A%20%22john%22%2C%20age%3A%2030%2C%20...obj0%20%7D%0Aconst%20obj2%20%3D%20%7B%20...obj1%20%7D)

**Comment by nathancahill** [comment]
This is intended behavior. The spread operator will create a new object.

**Comment by mourner** [comment]
I think this is a valid issue — the second line should allocate exactly one object, but it allocates two (`{}` and `{name: "john"}`).

**Comment by mourner** [comment]
Or at least the behavior is correct, but we could avoid redundant allocation to improve performance of generated code.

**Comment by nathancahill** [comment]
Ah, I see, I was looking at line 3. Line 2 could definitely be optimized.
