### ISSUE TITLE
Mark this repo deprecated?

### ISSUE THREAD

**Issue by Rich-Harris** [bublejs/buble#220]
I'm not personally able to devote any time to maintaining this project. @adrianheine and others — should we mark the repo (and package?) as deprecated so that people aren't misled? 

Prompted by https://github.com/mrdoob/three.js/pull/17276#issuecomment-534811893

**Comment by mourner** [comment]
In short, no — see my response on that ticket https://github.com/mrdoob/three.js/pull/17276#issuecomment-534889508

What we could do is add a note at the top of the readme that manages expectations — e.g. stating that the project is in maintenance mode, meaning we will accept PRs for bug fixes and do corresponding patch releases, but will not work on or accept PRs for major features such as async/await or class fields. See an example of such a note at the top of this repo https://github.com/documentationjs/documentation

**Comment by Rich-Harris** [comment]
Good idea — https://github.com/bublejs/buble/pull/221

**Comment by derrickb** [comment]
Well this is depressing! I really loved having a one-line plugin like this in my rollup config. The only feature I was waiting on was async/await. Thank you to everyone for the great work on this!
