### ISSUE TITLE
Can't handler destructuring

### ISSUE THREAD

**Issue by Hilbertangers** [bublejs/buble#223]
transpile ```[...Array(2)]```,
expect```[undefined, undefined]```,
but ```[].concat(Array(2)) === []```

because Iterators is Dangerous?

**Comment by mourner** [comment]
This specific case looks fine to me:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/25395/65700294-1391b100-e088-11e9-9487-97cdc04866fc.png">

**Comment by Hilbertangers** [comment]
emmmm.....
![image](https://user-images.githubusercontent.com/21299424/65737332-bdb51b80-e110-11e9-8d55-eaa0dc0f133e.png)
i use V8,What about you？ @mourner

**Comment by mourner** [comment]
@Hilbertangers it's true that this is not perfectly equivalent — but this makes the issue a duplicate of  #81. 

However, if you're surprised that `[] === []` is `false`, here's an article on how comparison operators work: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Using_the_equality_operators
