### ISSUE TITLE
Spread array with empty elements

### ISSUE THREAD

**Issue by Th0rN13** [bublejs/buble#238]
```[...Array(3)]``` compiles into ```[].concat( Array(3) )```
But ```[...Array(3)]``` - create array with 3 undefined elements, then ```[].concat( Array(3) )``` create array with empty elements (array with empty elements cannot be iterated via map, forEach, etc.)

So ```[...Array(3)].map((_, i) => i)``` create array ```[0, 1, 2]```, but compiled ```[].concat( Array(3) ).map((_, i) => i)``` create empty array

Also some issue with sparse array - spread convert empty elements to undefined

**Comment by mourner** [comment]
Yep, duplicate of #81
