### ISSUE TITLE
Improving Buble maintainability and v1.0

### ISSUE THREAD

**Issue by mourner** [bublejs/buble#241]
Continuing discussion in #220 and #185, I think the project reached a boiling point where we have to break compatibility to a minor extent to be able to land fixes (see recent PRs which are blocked by old Node — #240, #237, #236) and upgrade dependencies, so I propose making it ready for a v1.0.0 release by:

- Dropping Node 4–8 compatibility and committing to only supporting versions of Node that did not reach End of Life ([according to the status here](https://github.com/nodejs/release)).
- Upgrading all dependencies to latest semver releases (including `acorn`) and keeping them up-to-date from now on.
- Adding release automation with GitHub actions.
- Extending maintainer pool, including @luiscubal and @vitorveiga who made some great contributions recently.

cc @Rich-Harris @adrianheine @nathancahill

**Comment by Rich-Harris** [comment]
👍 from me on all points
