### ISSUE TITLE
[question] How do I support `import` and `export` with buble

### ISSUE THREAD

**Issue by fengxinming** [bublejs/buble#245]
Only use `buble` to transform `import` and `export` into `require` and `exports`.

```js
var buble = require( 'buble' );
var result = buble.transform( source ); // { code: ..., map: ... }
```

**Comment by huozhi** [comment]
hi @fengxinming , `import/export` and `require/exports` are module standards which first one belongs to ESModule and second one belongs to CommonJS. I believe buble is more focusing on compiling syntaxes to ES2015, without transpiling your ESModule to CJS modules. check https://buble.surge.sh/guide/#using-es-modules

similar issue here https://github.com/bublejs/buble/issues/143

**Comment by mourner** [comment]
Yep, out of scope for this library.
